services:
  redis:
      image: redis/redis-stack-server
      volumes:
        - ./data:/data
        - ./redis.conf:/redis-stack.conf
  api:
    build:
      context: .
      dockerfile: services/api/Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
  ingestor:
    build:
      context: .
      dockerfile: services/ingestor/Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379
      - SIMULATION=false
      - INACTIVITY_TIMEOUT=60
      - MONITOR_INTERVAL=10
      - MAX_RECONNECT_DELAY=60
    depends_on:
      - redis
