services:
  api:
    restart: unless-stopped
    expose:
      - "8000"
    environment:
      # --- NGINX PROXY AND LETSENCRYPT CONFIG ---
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
  ingestor:
    restart: unless-stopped
  redis:
    restart: unless-stopped

networks:
  default:
    name: nginx-proxy
    external: true
