# For use in production, with a reverse proxy.
# Example command: docker compose -f docker-compose.yaml -f docker-compose.prod.yaml up -d
services:
  api:
    restart: unless-stopped
    expose:
      - "8000"
    environment:
      # --- NGINX PROXY AND LETSENCRYPT CONFIG ---
      - VIRTUAL_HOST=api.formulastrats.com
      - LETSENCRYPT_HOST=api.formulastrats.com
      - LETSENCRYPT_EMAIL=davideftimov2112@gmail.com
  scheduler:
    restart: unless-stopped
  redis:
    restart: unless-stopped

networks:
  default:
    name: nginx-proxy
    external: true
