services:
  redis:
      image: redis/redis-stack-server
      volumes:
        - ./data:/data
        - ./redis.conf:/redis-stack.conf
  api:
    build:
      context: .
      dockerfile: formulastrats/app/Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
